### ISSUE TITLE
Release information not showing correctly in Software Updater Plugin

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/OctoPrint-robotheme#7]
I updated the theme with a new release and found that the Software Updater function of Octoprint is displaying the commit number rather than the version number.  It also did not recognize there was an update available.  

@Ximidar can we test this in the latest build?  The one you recently named should be a good control test.

**Comment by AllenMcAfee** [comment]
Just checked this against 1st batch units and the installed plugin is not an updatable version.

**Comment by Ximidar** [comment]
Part of the problem resides in the config.yaml of octoprint itself. 

```
softwareupdate:
    _config_version: 4
    check_providers:
      Kaa_Printevent: Kaa_Printevent
      customcontrol: customControl
      firmware_updater: firmwareupdater
      lani: lani
      netconnectd: netconnectd
      printhistory: printhistory
      requestspinner: requestspinner
      robolcd: RoboLCD
      robotheme: robotheme
      screensquish: ScreenSquish
      stats: stats
      systemcommandeditor: eeprom_marlin
    checks:
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        prerelease: false
        prerelease_channel: null
      robotheme:
        current: 92978e569fe27dbee4278693c4e3976ebf975ebc
```

The part with robotheme's commit needs to be taken out manually (possibly with a kaa update?) or the robotheme plugin will never update by release.
